apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleaner
  labels:
    group: {{ .Release.Name }}-jupyterhub
    component: pod-cleaner
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-cleaner
  labels:
    group: {{ .Release.Name }}-jupyterhub
    component: pod-cleaner
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
    - ""      # "" indicates the core API group
  resources:
    - pods
  verbs:
    - delete
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-cleaner
  labels:
    group: {{ .Release.Name }}-jupyterhub
    component: pod-cleaner
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: pod-cleaner
roleRef:
  kind: Role
  name: pod-cleaner
  apiGroup: rbac.authorization.k8s.io