apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: jupyter-proxy-config
          secret:
            secretName: jupyter-proxy-config
      containers:
      - name: auth-proxy
        image: registry.uninett.no/public/goidc-proxy:latest
        imagePullPolicy: Always
        env:
          - name: DATAPORTEN_CLIENTID
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataporten_client_id
          - name: DATAPORTEN_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataporten_client_secret
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
          - name: jupyter-proxy-config
            mountPath: /conf
        workingDir: /conf
      - name: jupyter
        image: registry.uninett.no/public/rlab-jupyter:latest
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 8888
