sudo: false
language: python
env:
  global:
  - HELM_VERSION="v2.8.2"
  - KUBEVAL_VERSION="0.13.0"
  - CONFTEST_VERSION="0.15.0"
  - secure: GW6rFTo/CZzTBrrt6XdHyQyRL4pTO7QBdpr4yZoc7a2WTromv1G7+XdH7DRVbmaE6117bD7YfNqQ+PLxRGJDV7JVwgcJReKu1ZsMnc1J4OS72MK8r4/9Wiptv13YNVrO30s2P8GzFryz6y9nefN/blqkmfO8BDpba7BDMdmX1ZDVsXds1/haDe3TmKOaZKd5z5vhJPy7njL+uY/SJtyxJxVYIEXy0kKj2MKeXqRWgN3ia2i0+yfkojCva8EYVKHHGNVvY1SrunJdggfMoTspmqrizPh2n7KeuHYh+9h7NhA1rHYXPf6jNkZHTyZE1Vy9d5BnUE0y8efZwWKK3P1PVhMquj0P+GMCeULOyk1BW/RQNdyZst8aXSTSitmdcfXJXQrfiFXxR3p40DhOwvBOywMU11/xcLUGcaTidSKTN+lqWUBx+PRuBuanWyO+1fBKocOb3d+SZVlLEjGdcZIW63NFUFIpDIbAzhYDdF8+lBSiNb1fIaS5HQyhFOMLHnb8Xu7JHl5ZJx32/+oVvIk2nfNePnljyb30Ovu/mEWoCcBmEL8/qwWNtPGtS90OEDWaojfUQzFjzNsJSQDQMs5aiJhBGoYcpmvpd3P4MSwGcAs9cTwolVh7X9kZy/Hz8gyI1HRMDCRTcQycU5o7X3tkGyt0jVovtZr5CBac82oK//o=
before_script:
- pip install yq jsonschema pyyaml
- wget "https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz"
- tar zxf helm-${HELM_VERSION}-linux-amd64.tar.gz
- mkdir bin
- mv linux-amd64/helm ./bin/helm
- wget "https://github.com/instrumenta/kubeval/releases/download/${KUBEVAL_VERSION}/kubeval-linux-amd64.tar.gz"
- tar zxf kubeval-linux-amd64.tar.gz
- mv kubeval ./bin/
- wget "https://github.com/instrumenta/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz"
- tar zxf conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz
- mv conftest ./bin/
- export PATH=$PATH:$PWD/bin/
script:
- "./build/update-chart-repo.sh"
after_success:
- "./build/push.sh"
