kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-hub-config
data:
  auth.state.enabled: "false"

  singleuser.network-tools.image.name: jupyterhub/k8s-network-tools
  singleuser.network-tools.image.tag: v0.6

  singleuser.cloud-metadata.enabled: "true"
  singleuser.cloud-metadata.ip: "169.254.169.254"

  singleuser.start-timeout: "300"
  hub.concurrent-spawn-limit: "64"

  singleuser.cmd: "jupyterhub-singleuser"

  singleuser.uid: "1000"
  singleuser.fs-gid: "1000"
  singleuser.service-account-name: {{ .Release.Name }}-hub
  singleuser.node-selector: "{}"

  singleuser.storage.type: "none"
  singleuser.storage.home_mount_path: "/home/jovyan"
  {{ if .Values.advanced.singleuser.memory.limit -}}
  singleuser.memory.limit: {{ .Values.advanced.singleuser.memory.limit | quote}}
  {{- end }}
  {{ if .Values.advanced.singleuser.memory.guarantee -}}
  singleuser.memory.guarantee: {{ .Values.advanced.singleuser.memory.guarantee | quote}}
  {{- end }}
  {{ if .Values.advanced.singleuser.cpu.limit -}}
  singleuser.cpu.limit: {{ .Values.advanced.singleuser.cpu.limit | quote}}
  {{- end }}
  {{ if .Values.advanced.singleuser.cpu.guarantee -}}
  singleuser.cpu.guarantee: {{ .Values.advanced.singleuser.cpu.guarantee | quote}}
  {{- end }}
  token.cookie_secret: ""
  hub.base_url: "/"
  hub.db_url: "sqlite://" # Use in memory
  auth.admin.access: "true"
