kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-hub-config
data:
  {{- /* Cull */}}
  {{- if .Values.advanced.killIdlePods.enabled }}
  cull.enabled: "true"
  cull.users: "false"
  cull.timeout: {{ .Values.advanced.killIdlePods.timeout | quote }}
  cull.every: "600"
  cull.concurrency: {{ .Values.advanced.killIdlePods.concurrency | quote }}
  {{- end }}

  {{- /* Auth */}}
  auth.state.enabled: "false"
  auth.admin.access: "true"
  auth.type: "dataporten"

  {{- /* Singleuser */}}
  singleuser.start-timeout: "300"
  singleuser.image-pull-policy: IfNotPresent
  singleuser.scheduler-strategy: pack
  singleuser.cmd: "jupyterhub-singleuser"
  singleuser.uid: "1000"
  singleuser.fs-gid: "1000"
  singleuser.service-account-name: "default"
  singleuser.node-selector: "{}"
  {{- if .Values.advanced.jupyterLab }}
  singleuser.cmd: "'jupyter lab --config /home/notebook/.jupyter/notebook_config.py'"
  {{- else }}
  singleuser.cmd: "'jupyter notebook --config /home/notebook/.jupyter/notebook_config.py'"
  {{- end }}
  {{- if ne .Values.persistentStorage.existingClaim "" }}
  singleuser.storage.type: "static"
  singleuser.storage.static.pvc-name: {{ .Values.persistentStorage.existingClaim }}
  singleuser.storage.static.subPath: 'home/{username}'
  {{- else }}
  singleuser.storage.type: "none"
  {{- end }}
  singleuser.storage.home_mount_path: "/home/notebook"
  {{- if .Values.advanced.singleuser.memory.limit }}
  singleuser.memory.limit: {{ .Values.advanced.singleuser.memory.limit | quote}}
  {{- end }}
  {{- if .Values.advanced.singleuser.memory.guarantee }}
  singleuser.memory.guarantee: {{ .Values.advanced.singleuser.memory.guarantee | quote}}
  {{- end }}
  {{- if .Values.advanced.singleuser.cpu.limit }}
  singleuser.cpu.limit: {{ .Values.advanced.singleuser.cpu.limit | quote}}
  {{- end }}
  {{- if .Values.advanced.singleuser.cpu.guarantee }}
  singleuser.cpu.guarantee: {{ .Values.advanced.singleuser.cpu.guarantee | quote}}
  {{- end }}
  singleuser.extra-labels: |
    hub.jupyter.org/network-access-hub: "true"

  kubespawner.common-labels: |
    group: {{ .Release.Name }}-jupyterhub
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

  hub.base_url: "/"
  hub.db_url: "sqlite:///jupyterhub.sqlite" # Use in memory
  hub.concurrent-spawn-limit: {{ .Values.advanced.notebook.spawnLimit | quote }}
  debug.enabled: {{ .Values.advanced.debug | quote }}
