kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-hub-secret
type: Opaque
data:
  proxy.token: {{ randAlphaNum 32 | b64enc | quote }}
  {{ if .Values.hub.cookieSecret }}
  hub.cookie-secret: {{ .Values.hub.cookieSecret | b64enc | quote }}
  {{- end }}
