kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-hub-secret
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
type: Opaque
data:
  proxy.token: {{ randAlphaNum 32 | b64enc | quote }}
