apiVersion: v1
description: Jupyterlab with Dataporten integration
home: https://github.com/UNINETT/helm-charts/tree/master/jupyterlab
icon: https://bollwyvl.github.io/jupyter.github.io/images/jupyter-sq-text.svg
maintainers:
- email: paal@128.no
  name: Pål Karlsrud @ UNINETT
name: jupyterlab
version: 0.2.1
