apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hub
  labels:
    release: {{ .Release.Name }}
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
spec:
  selector:
    name: {{ .Release.Name }}-hub
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
