workers:
  replicas: 1
  resources:
    requests:
        cpu: 100m
        memory: 1Gi
    limits:
        cpu: 200m
        memory: 1500Mi

master:
  resources:
    requests:
        cpu: 100m
        memory: 1Gi
    limits:
        cpu: 200m
        memory: 1500Mi
masterImage: quay.io/uninett/jupyter-spark:20180627-b86e87e
workerImage: quay.io/uninett/jupyter-spark:20180627-b86e87e
ingress:
  host: "host.example.com"

persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"

appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: "0000"
    client_secret: "0000"
    authorized_groups:
      - ""
