apiVersion: v1
description: Jupyter notebook with Tensorflow and Dataporten integration
name: jupyter-tensorflow
version: 0.1.1
maintainers:
  - name: Pål Karlsrud @ UNINETT
    email: paal@128.no
home: https://github.com/UNINETT/helm-charts/tree/master/jupyter-tensorflow
icon: https://bollwyvl.github.io/jupyter.github.io/images/jupyter-sq-text.svg
