kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-master
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    group: {{ template "fullname" . }}
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    app: {{ template "fullname" . }}-master

---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-master-ui
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    group: {{ template "fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: {{ template "fullname" . }}-master
