apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}-spark
spec:
  podSelector:
    matchLabels:
      group: {{ template "fullname" . }}-spark
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP

---
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}-spark-ui
spec:
  podSelector:
    matchLabels:
      group: {{ template "fullname" . }}-spark
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-ingress
      ports:
        - protocol: TCP
          port: 8000
