apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-spark-worker
spec:
  replicas: {{ .Values.workers.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-spark-worker
        group: {{ template "fullname" . }}-spark
    spec:
      containers:
        - name: spark-worker
          image: paalka/spark-worker
          imagePullPolicy: Always
          env:
            - name: SPARK_WORKER_MEMORY
              value: '1G'
            - name: SPARK_WORKER_CORES
              value: '2'
            - name: SPARK_MASTER_SERVICE_HOST
              value: {{ template "fullname" . }}-spark-master
          ports:
            - containerPort: 8081
          resources:
            requests:
                cpu: {{ .Values.workers.resources.requests.cpu }}
                memory: {{ .Values.workers.resources.requests.memory }}
            limits:
                cpu: {{ .Values.workers.resources.limits.cpu }}
                memory: {{ .Values.workers.resources.limits.memory }}
