ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 200m
    memory: 200M
  limits:
    cpu: 400m
    memory: 400M
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
  readOnly: false
  subPath: "/"
uid: 999
gid: 999
supplementalGroups: []
advanced:
  accessKey: "exampleaccesskey"
  secretKey: "examplesecretkey"
