apiVersion: v1
description: Jupyterlab with Dataporten integration
name: jupyterlab
version: 0.1.2
maintainers:
  - name: Pål Karlsrud @ UNINETT
    email: paal@128.no
home: https://github.com/UNINETT/helm-charts/tree/master/jupyterlab
icon: https://bollwyvl.github.io/jupyter.github.io/images/jupyter-sq-text.svg
