apiVersion: v1
description: Desktop VNC with Ubuntu
name: desktop-vnc
version: 0.1.1
maintainers:
- name: Uninett AS
  email: system@uninett.no
home: https://github.com/Uninett/helm-charts/tree/master/desktop-vnc
icon: https://bollwyvl.github.io/jupyter.github.io/images/jupyter-sq-text.svg
keywords:
  - Apache Spark
  - Scala
  - R
