apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: proxy
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      component: proxy
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/hub-secret: {{ include (print $.Template.BasePath "/hub/secret.yaml") . | sha256sum }}
      labels:
        name: proxy
        component: proxy
        group: {{ .Release.Name }}-jupyterhub
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        hub.jupyter.org/network-access-hub: "true"
        hub.jupyter.org/network-access-singleuser: "true"
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values: ['hub']
                    - key: release
                      operator: In
                      values: [ {{ .Release.Name | quote }} ]
      containers:
        - name: chp
          image: jupyterhub/configurable-http-proxy:3.0.0
          command:
            - "configurable-http-proxy"
            - "--ip=0.0.0.0"
            - "--port=8000"
            - "--api-ip=0.0.0.0"
            - "--api-port=8001"
            - "--default-target=http://$({{ .Release.Name | upper | replace "-" "_" }}_HUB_SERVICE_HOST):$({{ .Release.Name | upper | replace "-" "_" }}_HUB_SERVICE_PORT)"
            - "--error-target=http://$({{ .Release.Name | upper | replace "-" "_" }}_HUB_SERVICE_HOST):$({{ .Release.Name | upper | replace "-" "_" }}_HUB_SERVICE_PORT)"
          resources:
{{ toYaml .Values.advanced.proxy.resources | indent 12 }}
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-hub-secret
                  key: proxy.token
          ports:
            - containerPort: 8000
              name: proxy-public
            - containerPort: 8001
              name: api
      terminationGracePeriodSeconds: 60
