apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy-api
  labels:
    release: {{ .Release.Name }}
    group: {{ .Release.Name }}-jupyterhub
spec:
  selector:
    name: proxy
    component: proxy
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy-http
  # toYaml + indent seem a lot more unstable & error prone
  annotations: {{ toJson .Values.proxy.service.annotations }}
  labels:
    release: {{ .Release.Name }}
    group: {{ .Release.Name }}-jupyterhub
spec:
  type: ClusterIP
  selector:
    name: proxy
    component: proxy
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
