advanced:
  workers:
    replicas: 1
    resources:
      requests:
          cpu: 100m
          memory: 1Gi
      limits:
          cpu: 200m
          memory: 1500Mi

  master:
    resources:
      requests:
          cpu: 100m
          memory: 1Gi
      limits:
          cpu: 200m
          memory: 1500Mi
  dockerImage: quay.io/uninett/jupyter-spark:20190318-144efc8

uid: 999
gid: 999
username: notebook
supplementalGroups:
  - name: ""
    gid: ""
ingress:
  host: "host.example.com"

persistentStorage:
  - existingClaim: ""
    existingClaimName: "example-name"
    subPath: "/"

appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@uninett.no"
  dataporten:
    scopes:
      - ""
    id: "0000"
    owner: "0000-1234"
    client_secret: "0000"
    authorized_groups:
      - ""
authGroupProviders:
  - url: "https://groups-api.dataporten.no/groups/me/groups"
    scope: groups
