apiVersion: v1
description: A collection of various deep learning tools
name: deep-learning-tools
version: 0.2.9
maintainers:
  - name: UNINETT AS
    email: system@uninett.no
home: https://github.com/UNINETT/helm-charts-dockerfiles/tree/master/deep-learning-tools
icon: https://upload.wikimedia.org/wikipedia/commons/8/81/Deep_learning.png