ingress:
  host: "example.localhost.com"
resources:
  requests:
    cpu: 1
    memory: 2Gi
    gpu: 1
  limits:
    cpu: 2
    memory: 4Gi
    gpu: 1
dockerImage: quay.io/uninett/deep-learning-tools
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: ""
    client_secret: ""
    authorized_groups:
      - ""
