ingress:
  host: "example.localhost.com"
resources:
  requests:
    cpu: 1
    memory: 2Gi
    gpu: 1
  limits:
    cpu: 2
    memory: 4Gi
    gpu: 1
env:
  sparkMasterUrl: "local[*]"
  jupyterLab: false
dockerImage: quay.io/uninett/deep-learning-tools:20180526-db0f936
githubToken: ""
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: "0000"
    client_secret: "0000-abcd"
    authorized_groups:
      - ""
