ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 200m
    memory: 200M
  limits:
    cpu: 400m
    memory: 400M
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
  readOnly: false
  subPath: "/"
appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: "0000"
    client_secret: "0000"
    authorized_groups:
      - ""
advanced:
  dockerImage: quay.io/uninett/rstudio-server:20180526-7fb982a
