apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include "oidcconfig" . | sha256sum }}
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: oidcconfig
          secret:
            secretName: {{ template "fullname" . }}
        - name: notebook-config
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: notebook_config.py
              path: notebook_config.py
        - name: passwd
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: passwd
              path: passwd
        - name: group
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: group
              path: group
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
            readOnly: {{ .Values.persistentStorage.readOnly }}
      initContainers:
      - name: busybox
        image: busybox:1
        securityContext:
          runAsUser: {{ .Values.uid }}
        args:
          - /bin/sh
          - -c
          - -x
          - "mkdir -p /mnt/{{ .Values.persistentStorage.existingClaimName }}/home/{{ .Values.username }}/.jupyter && chmod g+w /mnt/{{ .Values.persistentStorage.existingClaimName }}/home"
        volumeMounts:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
      {{ end }}
      hostname: {{ template "fullname" . }}
      securityContext:
        runAsNonRoot: true
        fsGroup: {{ .Values.gid }}
        {{ $firstGroup := .Values.supplementalGroups | first }}
        {{- if $firstGroup.gid }}
        supplementalGroups:
          {{- range .Values.supplementalGroups }}
          - {{ .gid }}
          {{- end }}
        {{- end }}
      containers:
      - name: auth-proxy
        image: quay.io/uninett/goidc-proxy:v1.1.3
        imagePullPolicy: Always
        env:
          - name: DATAPORTEN_CLIENTID
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataporten_client_id
          - name: DATAPORTEN_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataporten_client_secret
        ports:
          - containerPort: 8080
        securityContext:
          runAsUser: 65534
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
          - name: oidcconfig
            mountPath: /conf
        workingDir: /conf
      - name: jupyter
        image: {{ .Values.advanced.dockerImage }}
        args: ["/usr/local/bin/start-notebook.sh"]
        {{- if ne .Values.persistentStorage.existingClaim "" }}
        workingDir: /home/{{ .Values.username }}
        {{ end }}
        env:
          {{ if .Values.advanced.env.jupyterLab }}
          - name: JUPYTER_ENABLE_LAB
            value: "1"
          {{ end }}
          - name: TZ
            value: Europe/Oslo
          - name: SPARK_MASTER_SERVICE
            value: {{ .Values.advanced.env.sparkMasterUrl }}
          - name: SPARK_OPTS
            value: --master={{ .Values.advanced.env.sparkMasterUrl }}
          - name: SPARK_DRIVER_MEMORY   # Need to set these values according to allocated resources
            value: 1g
          - name: SPARK_DRIVER_CORES
            value: '1'
          {{- if ne .Values.persistentStorage.existingClaim "" }}
          - name: XDG_CACHE_HOME
            value: /home/{{ .Values.username }}/.cache
          - name: HOME
            value: /home/{{ .Values.username }}
          - name: USER
            value: {{ .Values.username }}
          - name: PVC_MOUNT_PATH
            value: /mnt/{{ .Values.persistentStorage.existingClaimName }}
          {{- end }}
          - name: MEM_LIMIT
            value: {{ .Values.resources.limits.memory }}
          - name: OWNER_ID
            value: {{ .Values.appstore_generated_data.dataporten.owner }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 8888
        securityContext:
          runAsUser: {{ .Values.uid }}
        volumeMounts:
        {{- if ne .Values.persistentStorage.existingClaim "" }}
        - name: notebook-config
          mountPath: /home/{{ .Values.username }}/.jupyter/notebook_config.py
          subPath: notebook_config.py
        {{- else }}
        - name: notebook-config
          mountPath: /home/notebook/.jupyter/notebook_config.py
          subPath: notebook_config.py
        {{ end }}
        - name: passwd
          mountPath: /etc/passwd
          subPath: passwd
        - name: group
          mountPath: /etc/group
          subPath: group
        {{- if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
          {{ if ne .Values.persistentStorage.subPath "/" }}
          subPath: {{ .Values.persistentStorage.subPath }}
          {{ end }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /home/{{ .Values.username }}
          subPath: home/{{ .Values.username }}
        {{- end -}}
