ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 1Gi
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
env:
  sparkMasterUrl: "spark://example-master-url:7077"
dockerImage: quay.io/uninett/spark-notebook:20180409-79dd9dd
appstore_generated_data:
  dataporten:
    scopes:
      - "scope"
    id: "0000-abc"
    client_secret: "0000-0000"
    authorized_groups:
      - ""
