ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 1Gi
persistentStorage:
  enabled: false
  existingClaim: ""
dockerImage: quay.io/uninett/jupyter:latest
appstore_generated_data:
  dataporten:
    id: ""
    client_secret: ""
