ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 1Gi
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
env:
  sparkMasterUrl: "local[*]"
  jupyterLab: false
dockerImage: quay.io/uninett/jupyter-spark:20180523-0f6c26b
appstore_generated_data:
  dataporten:
    scopes:
      - "scope"
    id: "0000-abc"
    client_secret: "0000-0000"
    authorized_groups:
      - ""
