apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pod-cleaner
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    group: {{ .Release.Name }}-jupyterhub
    component: pod-cleaner
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-pod-cleaner
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    group: {{ .Release.Name }}-jupyterhub
    component: pod-cleaner
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
    - ""      # "" indicates the core API group
  resources:
    - pods
  verbs:
    - delete
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-pod-cleaner
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    group: {{ .Release.Name }}-jupyterhub
    component: pod-cleaner
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-pod-cleaner
roleRef:
  kind: Role
  name: {{ .Release.Name }}-pod-cleaner
  apiGroup: rbac.authorization.k8s.io
