apiVersion: v1
description: A collection of various deep learning tools
name: deep-learning-tools
version: 0.3.4
maintainers:
- name: Uninett AS
  email: system@uninett.no
home: https://github.com/Uninett/helm-charts-dockerfiles/tree/master/deep-learning-tools
icon: https://upload.wikimedia.org/wikipedia/commons/8/81/Deep_learning.png
packageVersions:
- pkg-cntk-version: 2.5.1
- pkg-onnx-version: 1.2.1
- pkg-mxnet-version: 1.2.0
- pkg-tensorflow-version: 1.9.0
- pkg-pytorch-version: 0.4.0
- pkg-cuda-version: 9.2.148
- pkg-cudnn-version: 7.1.4.18
- pkg-keras-version: 2.2.0
- pkg-caffe2-version: 0.8.dev
- pkg-theano-version: 1.0.2
