ingress:
  host: "example.localhost.com"
resources:
  requests:
    cpu: 1
    memory: 2Gi
    gpu: 1
  limits:
    cpu: 2
    memory: 4Gi
    gpu: 1
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
  readOnly: false
  subPath: "/"
appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: "0000"
    owner: "0000-1234"
    client_secret: "0000-abcd"
    authorized_groups:
      - ""
uid: 999
gid: 999
supplementalGroups:
  - ""
advanced:
  env:
    sparkMasterUrl: "local[*]"
    jupyterLab: false
  dockerImage: quay.io/uninett/deep-learning-tools:20180814-0b4564f
  githubToken: ""
authGroupProviders:
  - url: "https://groups-api.dataporten.no/groups/me/groups"
    scope: groups
