ingress:
  host: "example.localhost.com"
resources:
  requests:
    cpu: 1
    memory: 2Gi
    gpu: 1
  limits:
    cpu: 2
    memory: 4Gi
    gpu: 1
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: "0000"
    client_secret: "0000-abcd"
    authorized_groups:
      - ""
advanced:
  env:
    sparkMasterUrl: "local[*]"
    jupyterLab: false
  dockerImage: quay.io/uninett/deep-learning-tools:20180713-94e0aec
  githubToken: ""
