workers:
  replicas: 1
  resources:
    requests:
        cpu: 100m
        memory: 1Gi
    limits:
        cpu: 200m
        memory: 1500Mi

master:
  resources:
    requests:
        cpu: 100m
        memory: 1Gi
    limits:
        cpu: 200m
        memory: 1500Mi

jupyter:
  resources:
    requests:
        cpu: 100m
        memory: 1500Mi
    limits:
        cpu: 200m
        memory: 2G
  
ingress:
  host: "spark.example.com"

appstore_generated_data:
  dataporten:
    id: "abc"
    client_secret: "cba"
