workers:
  replicas: 1
  resources:
    requests:
        cpu: 100m
        memory: 1Gi
    limits:
        cpu: 200m
        memory: 1500Mi

master:
  resources:
    requests:
        cpu: 100m
        memory: 1Gi
    limits:
        cpu: 200m
        memory: 1500Mi

ingress:
  host: "host.example.com"

appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: ""
    client_secret: ""
    admins:
      - ""
