ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 1Gi
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
dockerImage: quay.io/uninett/rstudio-server:20180506-06a7e3d
appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: ""
    client_secret: ""
    authorized_groups:
      - ""
