apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-jupyterhub
spec:
  podSelector:
    matchLabels:
      group: {{ .Release.Name }}-jupyterhub
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-ingress
      ports:
        - protocol: TCP
          port: 8000

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-jupyterhub-all
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 8001
        - protocol: TCP
          port: 8888
