ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 1Gi
appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: ""
    client_secret: ""
    admins:
      - ""
