apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include "oidcconfig" . | sha256sum }}
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: oidcconfig
          secret:
            secretName: {{ template "fullname" . }}
        - name: proxy-config
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: default.conf
              path: default.conf
        - name: passwd
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: passwd
              path: passwd
        - name: group
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: group
              path: group
        - name: shadow
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: shadow
              path: shadow
        - name: indexhtml
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: indexhtml
              path: indexhtml
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
            readOnly: {{ .Values.persistentStorage.readOnly }}
        - name: {{ .Values.persistentStorage.existingClaimName }}-home
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
      initContainers:
      - name: busybox
        image: busybox:1
        securityContext:
          runAsUser: {{ .Values.uid }}
        args:
          - "/bin/mkdir"
          - "-p"
          - "/mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }} /mnt/{{ .Values.persistentStorage.existingClaimName }}/home/{{ .Values.username }}"
        volumeMounts:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
        {{ end }}
      securityContext:
        runAsNonRoot: true
        fsGroup: {{ .Values.gid }}
        {{ $firstGroup := .Values.supplementalGroups | first }}
        {{- if $firstGroup.gid }}
        supplementalGroups:
          {{- range .Values.supplementalGroups }}
          - {{ .gid }}
          {{- end }}
        {{- end }}
      containers:
      - name: auth-proxy
        image: quay.io/uninett/goidc-proxy:v1.1.3
        imagePullPolicy: Always
        env:
          - name: DATAPORTEN_CLIENTID
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataporten_client_id
          - name: DATAPORTEN_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataporten_client_secret
        ports:
          - containerPort: 8080
        securityContext:
          runAsUser: 65534
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
          - name: oidcconfig
            mountPath: /conf
        workingDir: /conf
      - name: rstudio-proxy
        image: quay.io/uninett/rstudio-proxy:20180629-e906891
        imagePullPolicy: Always
        volumeMounts:
          - name: proxy-config
            mountPath: /etc/nginx/conf.d
          - name: indexhtml
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
        securityContext:
          runAsUser: 65534
      - name: rstudio-server
        image: {{ .Values.advanced.dockerImage }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 8787
        - containerPort: 3838
        livenessProbe:
          httpGet:
            path: /unsupported_browser.htm
            port: 8787
          initialDelaySeconds: 30
          timeoutSeconds: 30
        securityContext:
          runAsUser: {{ .Values.uid }}
        env:
        - name: TZ
          value: Europe/Oslo
        - name: HOME
          value: /home/{{ .Values.username }}
        - name: USERNAME
          value: {{ .Values.username }}
        - name: OWNER_ID
          value: {{ .Values.appstore_generated_data.dataporten.owner }}
        {{- if ne .Values.persistentStorage.existingClaim "" }}
        - name: SHINY_APPS_PATH
          value: /mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }}/shiny-server
        - name: PVC_MOUNT_PATH
          value: /mnt/{{ .Values.persistentStorage.existingClaimName }}
        {{- end }}
        volumeMounts:
        - name: passwd
          mountPath: /etc/passwd
          subPath: passwd
        - name: group
          mountPath: /etc/group
          subPath: group
        - name: shadow
          mountPath: /etc/shadow
          subPath: shadow
        {{- if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
          {{ if ne .Values.persistentStorage.subPath "/" }}
          subPath: {{ .Values.persistentStorage.subPath }}
          {{ end }}
        - name: {{ .Values.persistentStorage.existingClaimName }}-home
          mountPath: /home/{{ .Values.username }}
          subPath: home/{{ .Values.username }}
        {{- end -}}


{{ if ne .Values.persistentStorage.existingClaim "" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-cleaner"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-cleaner"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      volumes:
      - name: {{ .Values.persistentStorage.existingClaimName }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentStorage.existingClaim }}
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.uid }}
        fsGroup: {{ .Values.gid }}
        {{ $firstGroup := .Values.supplementalGroups | first }}
        {{- if $firstGroup.gid }}
        supplementalGroups:
          {{- range .Values.supplementalGroups }}
          - {{ .gid }}
          {{- end }}
        {{- end }}
      containers:
      - name: cleaner-job
        image: "alpine:3.8"
        imagePullPolicy: Always
        command:
          - /bin/sh
        args:
          - -c
          - -x
          - "rm -rf /mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }}"
        volumeMounts:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
{{ end }}
