apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
     kubernetes.io/ingress.class: "nginx"
     kubernetes.io/tls-acme-staging: "true"
  labels:
    group: {{ template "fullname" . }}-spark
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ template "fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}-spark-master-ui
          servicePort: 80
