ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 200m
    memory: 200M
  limits:
    cpu: 400m
    memory: 400M
persistentStorage:
  - existingClaim: ""
    existingClaimName: "example-name"
    subPath: "/"
uid: 999
gid: 999
username: minio
supplementalGroups:
  - name: ""
    gid: ""
appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@uninett.no"
  dataporten:
    scopes:
      - ""
    id: "0000"
    client_secret: "0000"
    authorized_groups:
      - ""
advanced:
  accessKey: "accesskeyexample"
  secretKey: "secretkeyexample"
