ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 100m
    memory: 512M
  limits:
    cpu: 300m
    memory: 1G
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
  readOnly: false
  subPath: "/"
appstore_generated_data:
  dataporten:
    scopes:
      - "scope"
    id: "0000-abc"
    client_secret: "0000-0000"
    authorized_groups:
      - ""
uid: 999
advanced:
  env:
    sparkMasterUrl: "local[*]"
    jupyterLab: false
  dockerImage: quay.io/uninett/jupyter-spark:20180726-b815993
  githubToken: ""
