apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        checksum/config: {{ include "minioconfig" . | sha256sum }}
      labels:
        app: {{ template "fullname" . }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ template "fullname" . }}
            weight: 50
      {{ if ne .Values.persistentStorage.existingClaim "" }}
      volumes:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
      {{ end }}
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: MINIO_SECRET_KEY
        - name: TZ
          value: Europe/Oslo
        image: minio/minio:RELEASE.2018-05-11T00-29-24Z
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        args: [ "gateway", "nas", "--config-dir", "/tmp/.minio", "/mnt/{{ .Values.persistentStorage.existingClaimName }}" ]
        {{ else }}
        args: [ "gateway", "nas", "--config-dir", "/tmp/.minio", "/tmp" ]
        {{ end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 9000
        securityContext:
          runAsUser: 999
          # supplementalGroups:
          # - 999
        livenessProbe:
          tcpSocket:
            port: 9000
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        volumeMounts:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
        {{ end }}
