apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      {{ if ne .Values.persistentStorage.existingClaim "" }}
      volumes:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
      initContainers:
      - name: busybox
        image: busybox:1
        securityContext:
          runAsUser: 999
        args:
          - "/bin/mkdir"
          - "-p"
          - "/mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }}"
        volumeMounts:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        fsGroup: 999
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: MINIO_SECRET_KEY
        - name: TZ
          value: Europe/Oslo
        image: minio/minio:RELEASE.2018-06-22T23-48-46Z
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        args: [ 'server', '--quiet', '--config-dir', '/mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }}', '/mnt/{{ .Values.persistentStorage.existingClaimName }}' ]
        {{ else }}
        args: [ 'server', '--quiet', '--config-dir', '/tmp/.minio', '/tmp' ]
        {{ end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 9000
        securityContext:
          runAsUser: 999
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 30
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        volumeMounts:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
        {{ end }}
