apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.accessKey  | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.secretKey  | b64enc }}
