apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ randAlphaNum 20  | b64enc }}
  MINIO_SECRET_KEY: {{ randAlphaNum 40  | b64enc }}
