hub:
  service:
    type: ClusterIP
  baseUrl: /
  cookieSecret:
  publicURL:
  uid: 1000
  fsGid: 1000
  nodeSelector: {}
  concurrentSpawnLimit: 64
  activeServerLimit:
  db:
    type: sqlite-memory
    upgrade:
    pvc:
      annotations: {}
      selector: {}
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath:
      storageClassName:
    url:
  labels: {}
  extraConfig: |
    c.JupyterHub.authenticator_class =  'oauthenticator.generic.GenericOAuthenticator'
    c.OAuthenticator.client_id = ''
    c.OAuthenticator.login_service = 'Dataporten'
    c.OAuthenticator.client_secret = ''
    c.GenericOAuthenticator.token_url = 'https://auth.dataporten.no/oauth/token'
    c.GenericOAuthenticator.oauth_callback_url = 'https://paaltest.appstore-dep.ioudaas.no/hub/oauth_callback'
    c.GenericOAuthenticator.userdata_url  = 'https://auth.dataporten.no/openid/userinfo'
    c.GenericOAuthenticator.userdata_method = 'GET'
    c.GenericOAuthenticator.username_key = 'sub'
  extraConfigMap: {}
  extraEnv:
    OAUTH2_TOKEN_URL: "https://auth.dataporten.no/oauth/token"
    OAUTH2_AUTHORIZE_URL: "https://auth.dataporten.no/oauth/authorization"
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  image:
    name: jupyterhub/k8s-hub
    tag: v0.6
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
    limits:
      cpu: 0.4
      memory: 1Gi
  services: {}
  imagePullPolicy: IfNotPresent
  pdb:
    enabled: true

rbac:
  enabled: true

proxy:
  secretToken: '0e56cb468b840b156b4f11fd4ffc8a0d4a7496270920f6018e8f064de46e651f'
  service:
    type: LoadBalancer
    labels: {}
    annotations: {}
    nodePorts:
      http:
      https:
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: 3.0.0
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.2
        memory: 512Mi
      limits:
        cpu: 0.4
        memory: 1Gi
  nginx:
    image:
      name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: 0.9.0
      pullPolicy: IfNotPresent
    proxyBodySize: 64m
    resources: {}
  lego:
    image:
      name: jetstack/kube-lego
      # We need a couple of fixes related to ingress.provider that are in master
      # When 0.1.6 is released, switch to that!
      tag: master-2368
    resources: {}
  labels:
  nodeSelector: {}
  pdb:
    enabled: true
  https:
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: ''
    manual:
      key:
      cert:
    hosts: []


# Google OAuth secrets
auth:
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users:
  dummy:
    password: "hei"
  state:
    enabled: false
    cryptoKey:


singleuser:
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: v0.6
  cloudMetadata:
    enabled: true
    ip: 169.254.169.254
  extraLabels: {}
  extraEnv: {}
  lifecycleHooks:
  initContainers:
  nodeSelector: {}
  uid: 1000
  fsGid: 1000
  serviceAccountName: "hub"
  schedulerStrategy:
  storage:
    type: none
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: v0.6
  startTimeout: 300
  cpu:
    limit: 0.2
    guarantee: 0.2
  memory:
    limit: 1G
    guarantee: 1G
  cmd: jupyterhub-singleuser
  defaultUrl:

prePuller:
  hook:
    enabled: true
    extraEnv: {}
    image:
      name: jupyterhub/k8s-pre-puller
      tag: v0.6
  continuous:
    enabled: false
  pause:
    image:
      name: gcr.io/google_containers/pause
      tag: '3.0'

ingress:
  enabled: false
  annotations: {}
  hosts: []
  host: "paaltest.appstore-dep.ioudaas.no"
  tls:

cull:
  enabled: false
  users: false
  timeout: 3600
  every: 600
