hub:
  cookieSecret:
  db:
    type: sqlite-memory
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
    limits:
      cpu: 0.4
      memory: 1Gi

proxy:
  secretToken: '0e56cb468b840b156b4f11fd4ffc8a0d4a7496270920f6018e8f064de46e651f'
  chp:
    resources:
      requests:
        cpu: 0.2
        memory: 512Mi
      limits:
        cpu: 0.4
        memory: 1Gi

# Google OAuth secrets
auth:
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users:
  dummy:
    password: "hei"
  state:
    enabled: false
    cryptoKey:


singleuser:
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: v0.6
  cloudMetadata:
    enabled: true
    ip: 169.254.169.254
  extraLabels: {}
  extraEnv: {}
  lifecycleHooks:
  initContainers:
  nodeSelector: {}
  uid: 1000
  fsGid: 1000
  schedulerStrategy:
  storage:
    type: none
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: v0.6
  startTimeout: 300
  cpu:
    limit: 0.2
    guarantee: 0.2
  memory:
    limit: 1G
    guarantee: 1G
  cmd: jupyterhub-singleuser
  defaultUrl:

ingress:
  host: "paaltest.appstore-dep.ioudaas.no"

appstore_generated_data:
  dataporten:
    id: ""
    client_secret: ""
