apiVersion: v1
description: Git with a cup of tea - A painless self-hosted Git service
name: gittea
maintainers:
  - name: Metacenter
    email: spteam@metacenter.no
home: https://gitea.io
icon: https://avatars2.githubusercontent.com/u/12724356?s=400&v=4
version: 0.0.1
keywords:
  - Git
