advanced:
  workers:
    replicas: 1
    resources:
      requests:
          cpu: 100m
          memory: 1Gi
      limits:
          cpu: 200m
          memory: 1500Mi

  master:
    resources:
      requests:
          cpu: 100m
          memory: 1Gi
      limits:
          cpu: 200m
          memory: 1500Mi
  masterImage: quay.io/uninett/jupyter-spark:20180815-4bf0284
  workerImage: quay.io/uninett/jupyter-spark:20180815-4bf0284

uid: 999
gid: 999
supplementalGroups:
  - ""
ingress:
  host: "host.example.com"

persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
  readOnly: false
  subPath: "/"

appstore_generated_data:
  dataporten:
    scopes:
      - ""
    id: "0000"
    owner: "0000-1234"
    client_secret: "0000"
    authorized_groups:
      - ""
authGroupProviders:
  - url: "https://groups-api.dataporten.no/groups/me/groups"
    scope: groups
