{{- if .Values.advanced.externalPort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-loadbalancer
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
    use-uninett-load-balancer: true
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.advanced.externalPort.port }}
      targetPort: {{ .Values.advanced.externalPort.targetPort }}
      protocol: TCP
      name: {{ template "fullname" . }}-loadbalancer
  selector:
    app: {{ template "fullname" . }}-loadbalancer
{{- end }}
