apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  default.conf: {{ include "default.conf" . | quote }}
  passwd: {{ include "passwd" . | quote }}
  group: {{ include "group" . | quote }}
  shadow: {{ include "shadow" . | quote }}
  index.html: {{ include "indexhtml" . | quote }}
  shiny-server.conf: {{ include "shiny-server.conf" . | quote }}
