apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include "oidcconfig" . | sha256sum }}
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: oidcconfig
          secret:
            secretName: {{ template "fullname" . }}
        - name: proxy-config
          configMap:
            name: {{ template "fullname" . }}-proxy
            items:
            - key: default.conf
              path: default.conf
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
            readOnly: {{ .Values.persistentStorage.readOnly }}
      initContainers:
      - name: busybox
        image: busybox:1
        securityContext:
          runAsUser: 999
        args:
          - "/bin/mkdir"
          - "-p"
          - "/mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }}/shiny-server"
        volumeMounts:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
        {{ end }}
      securityContext:
        runAsNonRoot: true
        fsGroup: 999
      containers:
      - name: auth-proxy
        image: quay.io/uninett/goidc-proxy:v1.1.3
        imagePullPolicy: Always
        env:
          - name: DATAPORTEN_CLIENTID
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataporten_client_id
          - name: DATAPORTEN_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataporten_client_secret
        ports:
          - containerPort: 8080
        securityContext:
          runAsUser: 65534
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
          - name: oidcconfig
            mountPath: /conf
        workingDir: /conf
      - name: rstudio-proxy
        image: quay.io/uninett/rstudio-proxy:20180508-982419f
        imagePullPolicy: Always
        volumeMounts:
          - name: proxy-config
            mountPath: /etc/nginx/conf.d
        securityContext:
          runAsUser: 65534
      - name: rstudio-server
        image: {{ .Values.advanced.dockerImage }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 8787
        - containerPort: 3838
        livenessProbe:
          httpGet:
            path: /unsupported_browser.htm
            port: 8787
          initialDelaySeconds: 30
          timeoutSeconds: 30
        securityContext:
          runAsUser: 999
        env:
        - name: TZ
          value: Europe/Oslo
        {{- if ne .Values.persistentStorage.existingClaim "" }}
        - name: SHINY_APPS_PATH
          value: /mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }}/shiny-server
        volumeMounts:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
        {{- end -}}
