apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  dataporten_client_id: {{ .Values.appstore_generated_data.dataporten.id | b64enc }}
  dataporten_client_secret: {{ .Values.appstore_generated_data.dataporten.client_secret | b64enc }}
  goidc.json: {{ include "oidcconfig" . | b64enc }} 
